language: python
git:
  lfs_skip_smudge: true
cache:
  directories:
    - .git/lfs
python:
#  - "3.5" # fstring not available with this version
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - git lfs pull
install:
  - mkdir gatetools
  - git clone https://github.com/OpenGATE/GateTools.git gatetools
  - cd gatetools 
  - pip install -e .
  - cd ..
  - pip freeze
script: 
  - python -m unittest stitch_image -v
  - python -m unittest radioactiveDecay -v
  - python -m unittest anonymize -v
  - python -m unittest image_projection.py -v

  - python -m unittest faf_create_planar_geometrical_mean.py -v
#  - python -m unittest faf_register_planar_image.py -v
  - python -m unittest faf_ACF_image.py -v
  - python -m unittest faf_ACGM_image.py -v

notifications:
  email: false
