
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]


    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
          mkdir gatetools
          git clone https://github.com/OpenGATE/GateTools.git gatetools
          cd gatetools 
          pip install -e .
          cd ..
          pip install --upgrade pip
          pip install scikit-build
          pip install itk==5.1.2
          if [ "${{ matrix.python-version }}" == "3.6" ]; then
            wget https://nightly.link/SimonRit/RTK/workflows/build-test-package/master/LinuxWheel36.zip
          elif [ "${{ matrix.python-version }}" == "3.7" ]; then
            wget https://nightly.link/SimonRit/RTK/workflows/build-test-package/master/LinuxWheel37.zip
          elif [ "${{ matrix.python-version }}" == "3.8" ]; then
            wget https://nightly.link/SimonRit/RTK/workflows/build-test-package/master/LinuxWheel38.zip
          fi
          unzip Linux*.zip
          pip install itk_rtk*.whl
          #pip install itk.rtk
          pip freeze
    - name: Run the tests
      run: |
          python -m unittest stitch_image -v
          python -m unittest radioactiveDecay -v
          python -m unittest anonymize -v
          python -m unittest image_projection.py -v

          python -m unittest faf_create_planar_geometrical_mean.py -v
          #python -m unittest faf_register_planar_image.py -v
          python -m unittest faf_ACF_image.py -v
          python -m unittest faf_ACGM_image.py -v
          python -m unittest faf_calibration.py -v
          python -m unittest listmode2projection.py -v
